#!/usr/bin/env python3
"""
Plot side-by-side engineering fronts for RWMOP9 (M=2) and RWMOP8 (M=3).

Input CSVs are generated by experiments/extract_fronts_for_paper.m using the
median-IGD run criterion per algorithm.
"""

from __future__ import annotations

import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))
FRONTS_DIR = os.path.join(ROOT, "data", "processed", "fronts")
OUT_FIG = os.path.join(ROOT, "paper", "figures", "engineering_fronts_rwmop9_rwmop8.pdf")

ALGORITHMS = ["IVFSPEA2", "SPEA2", "NSGAIII", "ARMOEA"]

ALGO_DISPLAY = {
    "IVFSPEA2": "IVF/SPEA2",
    "SPEA2": "SPEA2",
    "NSGAIII": "NSGA-III",
    "ARMOEA": "AR-MOEA",
}

PALETTE = {
    "IVFSPEA2": "#2166AC",
    "SPEA2": "#B2182B",
    "NSGAIII": "#984EA3",
    "ARMOEA": "#999999",
}


def load_front(problem: str, m: str, algo: str) -> pd.DataFrame | None:
    path = os.path.join(FRONTS_DIR, f"{problem}_{m}_{algo}_median.csv")
    if not os.path.isfile(path):
        return None
    return pd.read_csv(path)


def main() -> None:
    os.makedirs(os.path.dirname(OUT_FIG), exist_ok=True)

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 8,
            "axes.titlesize": 9,
            "axes.labelsize": 8,
            "legend.fontsize": 7,
            "figure.dpi": 300,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.05,
        }
    )

    fig = plt.figure(figsize=(8.6, 3.8))
    ax1 = fig.add_subplot(1, 2, 1)
    ax2 = fig.add_subplot(1, 2, 2, projection="3d")

    for algo in ALGORITHMS:
        d = load_front("RWMOP9", "M2", algo)
        if d is None:
            continue
        s = 16 if algo == "IVFSPEA2" else 9
        z = 3 if algo == "IVFSPEA2" else 1
        ax1.scatter(
            d["f1"],
            d["f2"],
            s=s,
            c=PALETTE[algo],
            alpha=0.8,
            edgecolors="none",
            label=ALGO_DISPLAY[algo],
            zorder=z,
        )

    for algo in ALGORITHMS:
        d = load_front("RWMOP8", "M3", algo)
        if d is None:
            continue
        s = 14 if algo == "IVFSPEA2" else 8
        ax2.scatter(
            d["f1"],
            d["f2"],
            d["f3"],
            s=s,
            c=PALETTE[algo],
            alpha=0.82,
            edgecolors="none",
            label=ALGO_DISPLAY[algo],
        )

    ax1.set_xlabel("$f_1$")
    ax1.set_ylabel("$f_2$")
    ax1.set_title("(a) RWMOP9 ($M=2$)")
    ax1.grid(True, linestyle="--", alpha=0.25)

    ax2.set_xlabel("$f_1$", labelpad=2)
    ax2.set_ylabel("$f_2$", labelpad=2)
    ax2.set_zlabel("$f_3$", labelpad=1)
    ax2.view_init(elev=24, azim=-53)
    ax2.set_title("(b) RWMOP8 ($M=3$)", pad=4)
    ax2.tick_params(labelsize=6)

    handles, labels = ax1.get_legend_handles_labels()
    if handles:
        fig.legend(
            handles,
            labels,
            loc="lower center",
            ncol=4,
            frameon=True,
            bbox_to_anchor=(0.5, -0.02),
        )

    fig.suptitle(
        "Engineering fronts from median-IGD runs (per algorithm)",
        y=1.01,
        fontsize=10,
    )
    plt.tight_layout(rect=[0, 0.05, 1, 0.96], w_pad=1.0)
    fig.savefig(OUT_FIG)
    plt.close(fig)

    print(f"Saved: {OUT_FIG}")


if __name__ == "__main__":
    main()
