#!/usr/bin/env python3
"""
Plot DTLZ4 M=3 bimodal behavior: good vs bad convergence runs.

Input CSVs are generated by experiments/extract_fronts_for_paper.m using the
Q1/Q3 selection criterion (good = closest to Q1; bad = closest to Q3 with IGD > 0.1).
"""

from __future__ import annotations

import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))
FRONTS_DIR = os.path.join(ROOT, "data", "processed", "fronts")
OUT_FIG = os.path.join(ROOT, "paper", "figures", "dtlz4_bimodal_good_bad.pdf")
META_CSV = os.path.join(FRONTS_DIR, "DTLZ4_M3_selection_metadata.csv")


def load(name: str) -> pd.DataFrame | None:
    path = os.path.join(FRONTS_DIR, name)
    if not os.path.isfile(path):
        print(f"  WARNING: {path} not found")
        return None
    return pd.read_csv(path)


def load_selection_metadata() -> dict[str, str]:
    if not os.path.isfile(META_CSV):
        return {}

    meta = pd.read_csv(META_CSV)
    info: dict[str, str] = {}
    for _, row in meta.iterrows():
        sel = str(row.get("selection_type", "")).strip()
        run_id = row.get("run_id")
        igd = row.get("igd")
        if pd.isna(run_id) or pd.isna(igd):
            continue
        info[sel] = f"RunID {int(run_id)} | IGD={float(igd):.3g}"
    return info


def main() -> None:
    os.makedirs(os.path.dirname(OUT_FIG), exist_ok=True)

    good = load("DTLZ4_M3_IVFSPEA2_good.csv")
    bad = load("DTLZ4_M3_IVFSPEA2_bad.csv")
    pf = load("DTLZ4_M3_truePF.csv")
    selection_info = load_selection_metadata()

    if good is None or bad is None or pf is None:
        print("ERROR: Missing input CSVs. Run extract_fronts_for_paper.m first.")
        return

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 8,
            "axes.titlesize": 9,
            "axes.labelsize": 8,
            "legend.fontsize": 7,
            "figure.dpi": 300,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.05,
        }
    )

    fig = plt.figure(figsize=(8.6, 3.8))
    ax1 = fig.add_subplot(1, 2, 1, projection="3d")
    ax2 = fig.add_subplot(1, 2, 2, projection="3d")

    # True Pareto front (background)
    for ax in (ax1, ax2):
        ax.scatter(
            pf["f1"],
            pf["f2"],
            pf["f3"],
            s=4,
            c="#CCCCCC",
            alpha=0.3,
            edgecolors="none",
            label="True PF",
        )

    # Good run
    ax1.scatter(
        good["f1"],
        good["f2"],
        good["f3"],
        s=14,
        c="#2166AC",
        alpha=0.82,
        edgecolors="none",
        label="IVF/SPEA2",
    )

    # Bad run
    ax2.scatter(
        bad["f1"],
        bad["f2"],
        bad["f3"],
        s=14,
        c="#B2182B",
        alpha=0.82,
        edgecolors="none",
        label="IVF/SPEA2",
    )

    title_good = "(a) Good convergence (Q1)"
    if "good_q1" in selection_info:
        title_good = f"{title_good}\n{selection_info['good_q1']}"

    title_bad = "(b) Poor convergence (Q3, IGD > 0.1)"
    if "bad_q3_gt_0p1" in selection_info:
        title_bad = f"{title_bad}\n{selection_info['bad_q3_gt_0p1']}"

    for ax, title in [(ax1, title_good), (ax2, title_bad)]:
        ax.set_xlabel("$f_1$", labelpad=2)
        ax.set_ylabel("$f_2$", labelpad=2)
        ax.set_zlabel("$f_3$", labelpad=1)
        ax.view_init(elev=24, azim=-53)
        ax.set_title(title, pad=4, fontsize=8)
        ax.tick_params(labelsize=6)

    handles1, labels1 = ax1.get_legend_handles_labels()
    fig.legend(
        handles1,
        labels1,
        loc="lower center",
        ncol=2,
        frameon=True,
        bbox_to_anchor=(0.5, -0.02),
    )

    fig.suptitle(
        "DTLZ4 ($M{=}3$): bimodal convergence regimes",
        y=1.01,
        fontsize=10,
    )
    plt.tight_layout(rect=[0, 0.05, 1, 0.96], w_pad=1.0)
    fig.savefig(OUT_FIG)
    plt.close(fig)

    print(f"Saved: {OUT_FIG}")


if __name__ == "__main__":
    main()
